name: Trigger-All-Workflows

on:
  workflow_dispatch:
    inputs:
      ipq60xx_libwrt:
        description: 运行 IPQ60XX-LibWrt
        required: false
        type: boolean
        default: true
      build_packages:
        description: 运行 Build-Packages
        required: false
        type: boolean
        default: true
  schedule:
    - cron: "0 18 * * 5"

permissions:
  contents: read
  actions: read

jobs:

    IPQ60XX-LibWrt:
      if: ${{ github.event_name == 'schedule' || inputs.ipq60xx_libwrt }}
      uses: ./.github/workflows/IPQ60XX-LibWrt.yml
      permissions:
        contents: write
        actions: write

    Build-Packages:
      if: ${{ github.event_name == 'schedule' || inputs.build_packages }}
      uses: ./.github/workflows/Build-Packages.yml
      permissions:
        contents: write
        actions: read
      with:
        sdk_version: ALL
